name: My First Workflow

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Welcome Message
        run: |
          echo "ðŸŽ‰ Welcome to GitHub Actions!"
          echo "ðŸ“… Current time: $(date)"
          echo "ðŸ“‚ Files in repository:"
          ls -la
